//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantDBEntities1 : DbContext
    {
        public RestaurantDBEntities1()
            : base("name=RestaurantDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Restaurant_Order> Restaurant_Order { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<View_Users> View_Users { get; set; }
        public virtual DbSet<View_User_Orders_By_UserId> View_User_Orders_By_UserId { get; set; }
        public virtual DbSet<View_Orders_By_ResId_And_OrderDate> View_Orders_By_ResId_And_OrderDate { get; set; }
        public virtual DbSet<View_Restaurant_Details> View_Restaurant_Details { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Get_Order_Id(Nullable<int> restaurantId, Nullable<System.DateTime> orderDate)
        {
            var restaurantIdParameter = restaurantId.HasValue ?
                new ObjectParameter("RestaurantId", restaurantId) :
                new ObjectParameter("RestaurantId", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Order_Id", restaurantIdParameter, orderDateParameter);
        }
    
        public virtual ObjectResult<Get_User_Orders_By_Email_Result> Get_User_Orders_By_Email(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_User_Orders_By_Email_Result>("Get_User_Orders_By_Email", userIDParameter);
        }
    }
}
