//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Orders_By_ResId_And_OrderDate
    {
        public string Name { get; set; }
        public int RestaurantId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public short TableNumber { get; set; }
        public int NumberOfDiners { get; set; }
        public string UserEmail { get; set; }
    }
}
