//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Users
    {
        public string Name { get; set; }
        public string UserEmail { get; set; }
        public int UserId { get; set; }
        public string PhoneNumber { get; set; }
    }
}
